#!/bin/sh
# Retrieve location of this script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# Run the gradle task quietly
cd $SCRIPT_DIR && ./gradlew run -q --console=plain
